server:
  error:
    include-message: always

spring:
  security:
    user:
      name: jose
      password: maria17
      roles: ADMIN
  datasource:
    url: jdbc:h2:mem:nursery
    driver-class-name: org.h2.Driver
  h2:
    console:
      path: /h2
      enabled: true
  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect